version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'

  php:
    container_name: php
    image: php:fpm-bullseye
    volumes:
      - './src:/var/www/html'
